### ISSUE TITLE
Android M above support

### ISSUE THREAD

**Issue by rupeshpadhye** [digigene/account-authenticator#9]
Hi 
 I tried sample app on android M ,but account is not shown in settings section tried with 25.0.1 build tools

**Comment by alinhayati** [comment]
Hi,
Thanks for your attention.
This issue does not have anything to do with the library or android M.
In your accountauthenticatior.xml, you should use string resource for label instead of plain text.
Please visit the following:
[http://stackoverflow.com/questions/20695537/why-doesnt-my-android-custom-account-show-in-accounts-and-settings](here)
